# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
jobs:
  deploy:
    runs-on: ubuntu-latest
    env: 
      tag: $(date +%s)
    strategy:
      matrix:
        node-version: [10.x, 12.x]
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - run: npm install
      - run: npm ci
      - run: docker build . --file Dockerfile --tag registry.cn-hongkong.aliyuncs.com/littledian/route-proxy:latest
      - run: docker tag registry.cn-hongkong.aliyuncs.com/littledian/route-proxy:latest registry.cn-hongkong.aliyuncs.com/littledian/route-proxy:$tag
      - run: docker login -u=${{ secrets.DOCKER_USERNAME }} -p=${{ secrets.DOCKER_PASSWORD }}
      - run: docker push registry.cn-hongkong.aliyuncs.com/littledian/route-proxy:latest
      - run: docker push registry.cn-hongkong.aliyuncs.com/littledian/route-proxy:$tag
